### PR TITLE
add support for Github Actions, publish snapshots to OSSRH automatically

### LINKED ISSUE #575: Reconfigure Maven release process without org.sonatype.oss:oss-parent:9
`org.sonatype.oss:oss-parent:9` is deprecated:

> In the past all the plugin configuration and other setup was managed by a Maven parent POM with the latest coordinates of `org.sonatype.oss:oss-parent:9`. This project leaked SCM, URL and other details and its usage is discouraged. Maintenance of the project has stopped and it no longer works with latest tooling such as Maven versions or Java versions. If desired, please manage your own organization-level POM in a similar manner.

See https://central.sonatype.org/pages/apache-maven.html for details.

### PR DESCRIPTION
**Pull request by gotson**
This PR will allow automatic deployments to Sonatype OSSRH for snapshots only for now.

Detailed changes:
- removes the legacy dependency `org.sonatype.oss:oss-parent:9` and replaces it with `org.sonatype.plugins:nexus-staging-maven-plugin`
- moves the Maven javadoc and source plugins inside the `release` profile
- adds the Maven GPG plugin
- adds Github Workflow support to test on various OS and JDK. The Oracle JDK is not supported natively, so I added a specific job for it, which downloads the latest JDK 8u301 from Oracle, and perform tests with and without `sun.java2d.cmm=sun.java2d.cmm.kcms.KcmsServiceProvider`
- The `nexus-staging-maven-plugin` will automatically choose the right destintation (snapshot or releases repository) according to the version (if it ends with `-SNAPSHOT` or not). For now I added a condition to only trigger the job for `-SNAPSHOT` versions, so it won't impact your current release process.

With this new PR, the releases could also be done from CI without human interventions, if you want it. Maybe in a second step.

⚠️ **The following Github secrets will need to be setup in the repository**:
- `SONATYPE_USERNAME`: your username for Maven Central
- `SONATYPE_PASSWORD`: your password for Maven Central
- `GPG_KEY`: your GPG key used for signing. It needs to be exported by using `gpg --armor --export-secret-keys <keyId>`.
- `GPG_PASSPHRASE`: your GPG key passphrase

Closes #575, supersedes #580

### CODE REVIEW

**Comment by haraldk** [comment]
Thank you! This sounds very good! 👍🏻 

I will review the PR as soon as possible.

**Comment by gotson** [comment]
Note that for now I only use jdk 8 and 11. Jdk 15 is already out of support and not available via the github action. I tried adding jdk 16 and 17 but had some issues, it seems the project doesn't work well with those versions. I'll try to have a look at it separately.

**Comment by haraldk** [comment]
Hi @gotson,

Sorry for taking so long... I was just about to merge the PR now, but it now has conflicts (which is probably my fault, sorry). Are you able to resolve the conflicts, and I will merge the PR and make the switch to GHA.

Thanks!

**Comment by gotson** [comment]
> Hi @gotson,
> 
> Sorry for taking so long... I was just about to merge the PR now, but it now has conflicts (which is probably my fault, sorry). Are you able to resolve the conflicts, and I will merge the PR and make the switch to GHA.
> 
> Thanks!

No worries at all! I just fixed the merge conflict 👍🏻

**Comment by haraldk** [comment]
Brilliant! Thanks!

**Review by haraldk — APPROVED** [review]
👍🏻

**Comment by gotson** [comment]
I see the snapshot push to maven central failed, did you configure the necessary secrets on the repo?

**Comment by haraldk** [comment]
No, I was a little reluctant on exporting my private keys... Not sure what is the practice on that. Should I create a new set of keys, just for this? Or export my current signing key?

**Comment by gotson** [comment]
> No, I was a little reluctant on exporting my private keys... Not sure what is the best practice on that. Should I create a new set of keys, just for this? Or export my current signing key?

It's pretty safe to store secrets in the github repo. There are ways for people to uncover secrets, it they have access to your repo, where they could `echo` the content of a secret, but that's a lot of preconditions.

You can probably create a new set of keys just for that.

I'm not an expert in gpg, I only ever created a key for maven central, so I'm not sure how much attached you are to yours. Might be the time to do your own research and check out how secure it is, according to your expectations, to store it there.

In the meantime you can probably disable the push to maven central snapshot job in the CI, so the build would stay green.

**Comment by haraldk** [comment]
Well, as you say, I only ever used this key for Maven artifact signing, so... I guess it's not such a big deal.

**Comment by haraldk** [comment]
Looking good! 😀

**Pull request merged**
