### PR TITLE
Disable clamping when reading raw tiff data

### PR DESCRIPTION
**Pull request by bchapuis**
This PR adresses the issue described in #740 and  #775 using the second option described by @haraldk.

### CODE REVIEW

**Comment by haraldk** [comment]
Thank you @bchapuis ! 

I will have a look at the code and review as soon as I find the time. There's a holiday coming up, so don't worry if it takes some time. 🎄

**Comment by haraldk** [comment]
Thanks! 

Have looked at the code and I think it does solve the use case from #775. 👍🏻 

However, I think I would prefer if the flag could be named `normalize`. And instead of passing it to the `normalizeColor` method(s), just avoid invoking them at all in the raster reading case. I think that would be a more general solution. Would you be able to do that?

**Comment by bchapuis** [comment]
Sure, I wasn't sure if the photometric interpretation could be skipped. It is much better that way. Thanks a lot for the review.

**Comment by haraldk** [comment]
Excellent! 

I see the PR still only handles the (non-)normalization for the floating point case (`normalizeColor(int, int, float[])`), my idea above was to wrap all invocations (also `normalizeColor(int, int, byte[])`, `normalizeColor(int, int, short[])` and `normalizeColor(int, int, int[])` methods) in the same logic. 

I realize this isn't completely trivial due to some code duplication (that I am working to remove in a separate branch), but if you would like to try, that would be great! Otherwise I can probably fix that later.

**Comment by bchapuis** [comment]
Thank you for the feedback. 

I must admit that do this as a road crossing 🐌 , having no idea of the big picture. I included the normailzeColorPlanar method in the last commit and the tests are still passing 😅

**Comment by haraldk** [comment]
Looking good! 👍🏻 

We should probably add some tests for this as well, but I can always add those later. If you have time now though, I'd be very happy if you could add just one test making sure that `readRaster` does indeed return unnormalized/unclamped values for one of the floating point samples already in the test/resources/tiff folder.

**Comment by bchapuis** [comment]
Yes, I also had that in mind, I struggled a bit at finding a good normalization example in the ressource directory and didn't want to add an existing DEM file as they may be subject to license requirements. I will be on holiday, but I will see if I can generate a good sample with random data when I come back.

**Comment by bchapuis** [comment]
Generating a tiff containing random values was actually pretty easy with qgis. I added it to the `test/resources/tiff` directory, its size (246KB) is similar to the other files. As all the pixels are altered by the normalization, the test can iterate over all the values obtained with the `readRaster` method and assert that they are different than the pixels obtained with the `read` method. Is this sufficient?

**Comment by haraldk** [comment]
Happy new year! 🎉 

Changes looks good! I would prefer if the test tested that the values were equal to the known correct value, rather than (any value) different from the incorrect value. Maybe you could test a single row against a fixed float array or so? 

Other than that, this is perfect! 😀

**Comment by bchapuis** [comment]
@haraldk Great, thank you for the feedback! I modified the test with an two dimentional array of floats representing a 5 by 5 square of pixels.

**Review by haraldk — APPROVED** [review]
Brilliant, thank you! 😀

**Comment by bchapuis** [comment]
@haraldk Thanks a lot for your work and for patiently reviewing this PR 👍

**Comment by bchapuis** [comment]
@haraldk Out of curiosity, is there a timeline for the next release? I'd love to use TwelveMonkeys for reading geotiff files.

**Comment by haraldk** [comment]
Sorry, no explicit release date, but it's on my list quite near the top. 😀

**Comment by bchapuis** [comment]
Cool, thanks a lot for your work 😅

**Comment by haraldk** [comment]
@bchapuis https://github.com/haraldk/TwelveMonkeys/releases/tag/twelvemonkeys-3.11.0

**Comment by bchapuis** [comment]
@haraldk Awesome! Thanks a lot 🚀

**Pull request merged**
