### PR TITLE
New project for Batik 1.7

### PR DESCRIPTION
**Pull request by Toilal**

### CODE REVIEW

**Comment by haraldk** [comment]
Hi people!

I'm working on the final preparations for the 3.1 release.

I've been reluctant to integrate this PR, as it needed a custom-built Batik version to work. I realize Batik 1.8 is now released, would it be possible to have a working imageio-batik plugin against this version?

Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Latest master now depends on Batik 1.8 (but it might also work with 1.7), so I'm closing this pull request.

Sorry for taking so long, and thanks again for the help!

-- 
Harald K

**Comment by haraldk** [comment]
PS: See #190

**Comment by Toilal** [comment]
:+1: thanks.

**Pull request closed without merging**
