### PR TITLE
Batik has released version 1.15

### PR DESCRIPTION
**Pull request by KoenDG**
Tickets fixed in this release: https://issues.apache.org/jira/browse/BATIK-1334?jql=project%20%3D%20BATIK%20AND%20status%20in%20(Resolved%2C%20Closed)%20AND%20fixVersion%20%3D%201.15%20ORDER%20BY%20affectedVersion%20DESC%2C%20priority%20DESC

### CODE REVIEW

**Comment by haraldk** [comment]
Thanks,

However, there seems to be either artifacts missing for this release, or a problem with artifact propagation to Central, as all builds of this PR currently fails with:

> Error:  Failed to execute goal on project imageio-batik: Could not resolve dependencies for project com.twelvemonkeys.imageio:imageio-batik:jar:3.9.0-SNAPSHOT: The following artifacts could not be resolved: org.apache.xmlgraphics:batik-rasterizer-ext:jar:1.15, org.apache.xmlgraphics:batik-extension:jar:1.15, org.apache.xmlgraphics:batik-anim:jar:1.15, org.apache.xmlgraphics:batik-svggen:jar:1.15, org.apache.xmlgraphics:batik-transcoder:jar:1.15: Could not find artifact org.apache.xmlgraphics:batik-rasterizer-ext:jar:1.15 in central (https://repo.maven.apache.org/maven2)

**Comment by KoenDG** [comment]
Indeed, it doesn't seem to be deployed yet.

Maybe a few days before the artifacts are out? I'm not sure, I just saw the email come in.

**Comment by haraldk** [comment]
Should probably just enable dependabot for automatic PRs when new versions are out. 😀

**Comment by KoenDG** [comment]
Looks like the artifacts are out now.

**Comment by haraldk** [comment]
As always: As soon as I find time. 

In the meantime, there should be no problem just upgrading your runtime dependencies to 1.15 (there are no changes in the code or binaries for this PR, it is strictly a dependency bump...).

**Pull request merged**
