### PR TITLE
TMI-61: CCITT Group 3/4 Fax Decoder

### PR DESCRIPTION
**Pull request by Schmidor**

### CODE REVIEW

**Comment by haraldk** [comment]
Thanks! I overlooked a few `e.printStackTrace()`s, I have removed these locally now. Otherwise, looking good.

**Comment by haraldk** [comment]
Hi Oliver, 

@Schmidor Sorry for commenting on an old issue, but I didn't find another way to contact you...

I found a TIFF with T.6/Group 4 compression that throws `IndexOutOfBoundsException` (see #159). Do you have some time to look at it?


Best regards,

-- 
Harald K

**Comment by Schmidor** [comment]
Hi Harald,
@haraldk No problem, i've now changed the setting which has hidden my mail address in commits.

I'm now starting into summer vacation. So it should take about two weeks till I'm able to look into the issue.

**Comment by haraldk** [comment]
Ok,

I'll look into the issue if I have time, otherwise it's there waiting for you when you come back... ;-)

In the mean time, have a nice summer vacation!

-- 
Harald K

**Pull request merged**
